# Julia básico

In [2]:
using Pkg
Pkg.activate(".")

  Activating new project at `~/Dropbox/JULIA/JULIA-EP`


Julia es un lenguaje de programación gratuito y de código abierto para todo propósito.

![](julia-logo-color.png)

# Julia como calculadora

## Operaciones aritméticas

In [3]:
3+4

7

In [4]:
4-7

-3

In [5]:
2*3

6

In [6]:
4/5

0.8

In [7]:
0/0

NaN

In [8]:
1/0

Inf

In [9]:
Inf - Inf

NaN

In [10]:
3^4

81

In [11]:
1/(1/(1+2)^2)

9.0

## Funciones vectorizadas

anteponer . (punto) a la función

In [12]:
2 .^ [1, 2, 3]

3-element Vector{Int64}:
 2
 4
 8

## Otras funciones

In [13]:
factorial(20)

2432902008176640000

In [14]:
factorial(21)

OverflowError: OverflowError: 21 is too large to look up in the table; consider using `factorial(big(21))` instead

In [15]:
factorial(big(21))

51090942171709440000

In [16]:
factorial(big(1_000_000));

## Macros

In [17]:
@time factorial(big(1_000_000));

  0.093515 seconds (1.33 k allocations: 56.663 MiB, 2.86% gc time)


In [18]:
@elapsed(factorial(big(1_000_000)))

0.100699583

In [19]:
@show 1+2

1 + 2 = 3


3

In [20]:
@which 2+2

+(x::T, y::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8}
     @ Base int.jl:87

## Pipes

In [21]:
log(2)

0.6931471805599453

In [22]:
2 |> log

0.6931471805599453

In [23]:
log(sin(cos(pi/6)))

-0.2721237579316842

In [24]:
pi/6 |> cos |> sin |> log

-0.2721237579316842

# Más funciones

In [25]:
√2

1.4142135623730951

In [26]:
sqrt(2)

1.4142135623730951

In [27]:
pi ^ ℯ

22.459157718361038

### Funciones trigonométricas

In [28]:
sin(pi/4)

0.7071067811865475

In [29]:
cosd(30)

0.8660254037844386

In [30]:
7%3

1

### Números complejos

In [31]:
2+3im

2 + 3im

In [32]:
(4-3im)*(-4-im)

-19 + 8im

In [33]:
2//5+3//4im

2//5 - 3//4*im

In [34]:
sqrt(im)

0.7071067811865476 + 0.7071067811865475im

### Números racionales

In [35]:
1//3+2//7

13//21

# Comparaciones lógicas

In [36]:
1 == 2

false

In [37]:
3 != 4

true

In [38]:
pi > 4

false

In [39]:
[1 2 3 4] .> 2.5

1×4 BitMatrix:
 0  0  1  1

# Tipos

In [40]:
typeof(1)

Int64

In [41]:
typeof(2.4)

Float64

In [42]:
typeof('a')

Char

In [43]:
typeof("abc")

String

In [44]:
typeof(true)

Bool

## Variables

En Julia _todo_ es un objeto y se le puede asignar un nombre. Un número es un objeto, una suma es un objeto, un vector es un objeto, una imagen es un objeto, un histograma es un objeto, … y se les puede asignar un nombre con  (=). 

In [45]:
x = 2


2

In [46]:
println(x)

2


In [47]:
x = x + 1

3

In [48]:
mi_variable = 8

8

In [49]:
δ = 3

3

In [50]:
z0 = 'a'

'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

In [51]:
z1 = 'b'

'b': ASCII/Unicode U+0062 (category Ll: Letter, lowercase)

In [52]:
z2 = "Amo "

"Amo "

In [53]:
z3 = "Julia"

"Julia"

In [54]:
z2 * z3

"Amo Julia"

In [55]:
methods(*)

# 188 methods for generic function "*" from Base:
   [1] *(r::Regex)
     @ regex.jl:861
   [2] *(x::Bool, z::Complex{Bool})
     @ complex.jl:312
   [3] *(x::Bool, y::Bool)
     @ bool.jl:170
   [4] *(x::Bool, y::AbstractIrrational)
     @ irrationals.jl:201
   [5] *(x::Bool, z::Complex)
     @ complex.jl:319
   [6] *(x::Bool, y::T) where T<:AbstractFloat
     @ bool.jl:181
   [7] *(z::Complex{Bool}, x::Bool)
     @ complex.jl:313
   [8] *(z::Complex{Bool}, x::Real)
     @ complex.jl:331
   [9] *(c::BigInt, x::BigFloat)
     @ mpfr.jl:613
  [10] *(a::BigInt, b::BigInt, c::BigInt, d::BigInt, e::BigInt)
     @ gmp.jl:544
  [11] *(a::BigInt, b::BigInt, c::BigInt, d::BigInt)
     @ gmp.jl:543
  [12] *(a::BigInt, b::BigInt, c::BigInt)
     @ gmp.jl:542
  [13] *(x::BigInt, y::BigInt)
     @ gmp.jl:502
  [14] *(x::BigInt, c::Union{Int16, Int32, Int64, Int8})
     @ gmp.jl:563
  [15] *(x::BigInt, c::Union{UInt16, UInt32, UInt64, UInt8})
     @ gmp.jl:561
  [16] *(a::BigFloat, b::BigFloat, c::BigFloat, d::BigFloat, e::BigFloat)
     @ mpfr.jl:764
  [17] *(x::BigFloat, y::BigFloat)
     @ mpfr.jl:577
  [18] *(a::BigFloat, b::BigFloat, c::BigFloat)
     @ mpfr.jl:751
  [19] *(a::BigFloat, b::BigFloat, c::BigFloat, d::BigFloat)
     @ mpfr.jl:757
  [20] *(x::BigFloat, c::BigInt)
     @ mpfr.jl:608
  [21] *(x::BigFloat, c::Union{UInt16, UInt32, UInt64, UInt8})
     @ mpfr.jl:584
  [22] *(x::BigFloat, c::Union{Int16, Int32, Int64, Int8})
     @ mpfr.jl:592
  [23] *(x::BigFloat, c::Union{Float16, Float32, Float64})
     @ mpfr.jl:600
  [24] *(B::BitMatrix, J::LinearAlgebra.UniformScaling)
     @ ~/.julia/juliaup/julia-1.12.6+0.aarch64.apple.darwin14/Julia-1.12.app/Contents/Resources/julia/share/julia/stdlib/v1.12/LinearAlgebra/src/uniformscaling.jl:264
  [25] *(::Missing, ::Missing)
     @ missing.jl:122
  [26] *(::Missing)
     @ missing.jl:101
  [27] *(d::Missing, x::Union{AbstractChar, AbstractString})
     @ missing.jl:174
  [28] *(::Missing, ::Number)
     @ missing.jl:123
  [29] *(x::Rational{BigInt}, y::Rational{BigInt})
     @ gmp.jl:1062
  [30] *(r::StepRangeLen{<:Real, <:Base.TwicePrecision}, x::Real)
     @ twiceprecision.jl:535
  [31] *(A::LinearAlgebra.UpperTriangular{<:Any, <:Union{LinearAlgebra.Adjoint{<:Any, <:StridedMatrix{T}}, LinearAlgebra.Transpose{<:Any, <:StridedMatrix{T}}, StridedArray{T, 2}} where T}, x::Number)
     @ ~/.julia/juliaup/julia-1.12.6+0.aarch64.apple.darwin14/Julia-1.12.app/Contents/Resources/julia/share/julia/stdlib/v1.12/LinearAlgebra/src/triangular.jl:1332
  [32] *(A::LinearAlgebra.UpperTriangular, x::Number)
     @ ~/.julia/juliaup/julia-1.12.6+0.aarch64.apple.darwin14/Julia-1.12.app/Contents/Resources/julia/share/julia/stdlib/v1.12/LinearAlgebra/src/triangular.jl:1331
  [33] *(A::LinearAlgebra.LQ{TA, S, C} where {S<:AbstractMatrix{TA}, C<:AbstractVector{TA}}, B::AbstractVecOrMat{TB}) where {TA, TB}
     @ ~/.julia/juliaup/julia-1.12.6+0.aarch64.apple.darwin14/Julia-1.12.app/Contents/Resources/julia/share/julia/stdlib/v1.12/LinearAlgebra/src/lq.jl:167
  [34] *(R::LinearAlgebra.AbstractRotation, A::AbstractMatrix)
     @ ~/.julia/juliaup/julia-1.12.6+0.aarch64.apple.darwin14/Julia-1.12.app/Contents/Resources/julia/share/julia/stdlib/v1.12/LinearAlgebra/src/givens.jl:13
  [35] *(R::LinearAlgebra.AbstractRotation, A::AbstractVector)
     @ ~/.julia/juliaup/julia-1.12.6+0.aarch64.apple.darwin14/Julia-1.12.app/Contents/Resources/julia/share/julia/stdlib/v1.12/LinearAlgebra/src/givens.jl:12
  [36] *(A::LinearAlgebra.Bidiagonal, B::Number)
     @ ~/.julia/juliaup/julia-1.12.6+0.aarch64.apple.darwin14/Julia-1.12.app/Contents/Resources/julia/share/julia/stdlib/v1.12/LinearAlgebra/src/bidiag.jl:437
  [37] *(r::AbstractRange{<:Real}, x::Dates.Period)
     @ ~/.julia/juliaup/julia-1.12.6+0.aarch64.apple.darwin14/Julia-1.12.app/Contents/Resources/julia/share/julia/stdlib/v1.12/Dates/src/ranges.jl:68
  [38] *(::Number, ::Missing)
     @ missing.jl:124
  [39] *(x::S, F::LinearAlgebra.Hessenberg{<:Any, <:AbstractMa

In [56]:
*(2,3)

6

# Datos

Los datos pueden venir presentados en arreglos:vectores, listas,matrices y/o 
dataframes, etc.

## Vectores

In [57]:
v0 = Vector(undef, 10)

10-element Vector{Any}:
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef

In [58]:
sizeof(v0)

80

In [59]:
v1 = [1,2,3]

3-element Vector{Int64}:
 1
 2
 3

In [60]:
v2 = [1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [61]:
v3 = 1:5

1:5

In [62]:
collect(v3)

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [63]:
v4 = 3:5:40
collect(v4)

8-element Vector{Int64}:
  3
  8
 13
 18
 23
 28
 33
 38

In [64]:
v5 = collect(2.1:pi:30.8)

10-element Vector{Float64}:
  2.1
  5.241592653589793
  8.383185307179586
 11.524777960769379
 14.666370614359172
 17.807963267948967
 20.94955592153876
 24.091148575128553
 27.232741228718346
 30.37433388230814

## Acceder a los elementos de un vector

In [65]:
v5[3]

8.383185307179586

In [66]:
v5[2:4]

3-element Vector{Float64}:
  5.241592653589793
  8.383185307179586
 11.524777960769379

In [67]:
v6=zeros(5)

5-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0

## Datos faltantes

In [68]:
v7=[2, 3, missing]

3-element Vector{Union{Missing, Int64}}:
 2
 3
  missing

In [69]:
sum(v7)

missing

In [70]:
sum(skipmissing(v7))

5

In [71]:
v8=collect('a':'f')

6-element Vector{Char}:
 'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
 'b': ASCII/Unicode U+0062 (category Ll: Letter, lowercase)
 'c': ASCII/Unicode U+0063 (category Ll: Letter, lowercase)
 'd': ASCII/Unicode U+0064 (category Ll: Letter, lowercase)
 'e': ASCII/Unicode U+0065 (category Ll: Letter, lowercase)
 'f': ASCII/Unicode U+0066 (category Ll: Letter, lowercase)

In [72]:
v9=rand(5)

5-element Vector{Float64}:
 0.7158248804191373
 0.9521781585666528
 0.41497141645789015
 0.17323133065109508
 0.4661168036012182

## Funciones para vectores

In [73]:
vect=[2,3,4,3,5,7,5,3,4,5,1]

11-element Vector{Int64}:
 2
 3
 4
 3
 5
 7
 5
 3
 4
 5
 1

In [74]:
length(vect)

11

In [75]:
sort(vect)

11-element Vector{Int64}:
 1
 2
 3
 3
 3
 4
 4
 5
 5
 5
 7

In [76]:
sort!(vect)

11-element Vector{Int64}:
 1
 2
 3
 3
 3
 4
 4
 5
 5
 5
 7

In [77]:
unique(vect)

6-element Vector{Int64}:
 1
 2
 3
 4
 5
 7

In [78]:
sum(vect)

42

In [79]:
prod(vect)

756000

In [80]:
cumsum(vect)

11-element Vector{Int64}:
  1
  3
  6
  9
 12
 16
 20
 25
 30
 35
 42

In [81]:
extrema(vect)

(1, 7)

## Matrices

In [82]:
m1 = [ 1 2 3; -4 5.0 pi; -2.8 4 0]

3×3 Matrix{Float64}:
  1.0  2.0  3.0
 -4.0  5.0  3.14159
 -2.8  4.0  0.0

In [83]:
ndims(m1)

2

In [84]:
size(m1)

(3, 3)

In [85]:
length(m1)

9

In [86]:
m2=zeros(2,3)

2×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [87]:
m3=rand(2,2)

2×2 Matrix{Float64}:
 0.517089  0.543615
 0.740435  0.39916

In [88]:
m4 = ones(2,3)

2×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0

## Comprensiones

Se utilizan para generar arreglos.

In [89]:
m5=[ x^2 for x in [1,2,3]]

3-element Vector{Int64}:
 1
 4
 9

In [90]:
m6=[(i,j) for i in 1:6, j in 1:6]

6×6 Matrix{Tuple{Int64, Int64}}:
 (1, 1)  (1, 2)  (1, 3)  (1, 4)  (1, 5)  (1, 6)
 (2, 1)  (2, 2)  (2, 3)  (2, 4)  (2, 5)  (2, 6)
 (3, 1)  (3, 2)  (3, 3)  (3, 4)  (3, 5)  (3, 6)
 (4, 1)  (4, 2)  (4, 3)  (4, 4)  (4, 5)  (4, 6)
 (5, 1)  (5, 2)  (5, 3)  (5, 4)  (5, 5)  (5, 6)
 (6, 1)  (6, 2)  (6, 3)  (6, 4)  (6, 5)  (6, 6)

## Acceder a los elementos de una matriz

In [91]:
m6[2,:]

6-element Vector{Tuple{Int64, Int64}}:
 (2, 1)
 (2, 2)
 (2, 3)
 (2, 4)
 (2, 5)
 (2, 6)

In [92]:
m6[:,3]

6-element Vector{Tuple{Int64, Int64}}:
 (1, 3)
 (2, 3)
 (3, 3)
 (4, 3)
 (5, 3)
 (6, 3)

In [93]:
v=Vector(1:16)
mv=reshape(v, (4,4))

4×4 Matrix{Int64}:
 1  5   9  13
 2  6  10  14
 3  7  11  15
 4  8  12  16

In [94]:
mv[1:2, 2:3]

2×2 Matrix{Int64}:
 5   9
 6  10

# Diccionarios en Julia

## Creación de diccionarios

Un diccionario está constituido por parejas (llave(key), valor(value))

In [95]:
D1 = Dict("a" => 1, "b" => 2, 1 => "a")

Dict{Any, Any} with 3 entries:
  "b" => 2
  "a" => 1
  1   => "a"

In [96]:
D1["c"] = 3          
D1

Dict{Any, Any} with 4 entries:
  "c" => 3
  "b" => 2
  "a" => 1
  1   => "a"

In [97]:
D1["c"] = "Hello"  
D1  

Dict{Any, Any} with 4 entries:
  "c" => "Hello"
  "b" => 2
  "a" => 1
  1   => "a"

In [98]:
D1 = delete!(D1, "c")  
D1

Dict{Any, Any} with 3 entries:
  "b" => 2
  "a" => 1
  1   => "a"

In [99]:
D2 = Dict("a" => 1, "b" => 2, "c" => 3, "d" => 4, "e" => 5)


Dict{String, Int64} with 5 entries:
  "c" => 3
  "e" => 5
  "b" => 2
  "a" => 1
  "d" => 4

In [100]:
D2["a"]

1

In [101]:
keys(D2)

KeySet for a Dict{String, Int64} with 5 entries. Keys:
  "c"
  "e"
  "b"
  "a"
  "d"

In [102]:
values(D2)

ValueIterator for a Dict{String, Int64} with 5 entries. Values:
  3
  5
  2
  1
  4

In [103]:
for (key, value) in D2
    println("$key => $value")
end

c => 3
e => 5
b => 2
a => 1
d => 4


In [104]:
dic1 = Dict("a" => 1, "b" => 2)
dic2 = Dict("b" => 3, "c" => 4)

unir_dics = merge(dic1, dic2)  

Dict{String, Int64} with 3 entries:
  "c" => 4
  "b" => 3
  "a" => 1

## Diccionario de colores en Julia

In [105]:
using Colors

In [106]:
dic_colores = Colors.color_names

Dict{String, Tuple{Int64, Int64, Int64}} with 666 entries:
  "darkorchid"     => (153, 50, 204)
  "chocolate"      => (210, 105, 30)
  "chocolate2"     => (238, 118, 33)
  "grey69"         => (176, 176, 176)
  "grey97"         => (247, 247, 247)
  "olivedrab3"     => (154, 205, 50)
  "deeppink2"      => (238, 18, 137)
  "mediumpurple2"  => (159, 121, 238)
  "ivory1"         => (255, 255, 240)
  "gray95"         => (242, 242, 242)
  "darkgoldenrod4" => (139, 101, 8)
  "lemonchiffon2"  => (238, 233, 191)
  "palegreen4"     => (84, 139, 84)
  "cornsilk4"      => (139, 136, 120)
  "red1"           => (255, 0, 0)
  "wheat1"         => (255, 231, 186)
  "lightpink4"     => (139, 95, 101)
  "wheat2"         => (238, 216, 174)
  "purple2"        => (145, 44, 238)
  ⋮                => ⋮

In [107]:
haskey(dic_colores, "red1")

true

In [108]:
dic_colores["rojo"]

KeyError: KeyError: key "rojo" not found

In [109]:
colorant"red"

In [110]:
range(colorant"red", stop=colorant"green", length=15)

[selector de colores](https://www.w3schools.com/colors/colors_picker.asp)

In [111]:
hex(RGB(1,0.5,0))

"FF8000"

In [112]:
colorant"rgb(145,44,238)"

# Homework 

Here are 10 questions about Julia dictionaries, ranging from basic to advanced:

## Basic Questions

1.	How do you create a dictionary in Julia with string keys and integer values?
2.	How do you add a new key-value pair to an existing dictionary?
3.	How can you check if a key exists in a Julia dictionary?
4.	What happens when you try to access a key that does not exist in a dictionary? How can you handle this safely?
5.	How do you remove a key-value pair from a dictionary?

## Intermediate Questions

6.	How can you iterate over the keys and values of a dictionary?
7.	What is the difference between get() and direct indexing (dict[key]) when accessing values in a dictionary?
8.	How do you merge two dictionaries in Julia?


# Conjuntos de datos

In [113]:
using RDatasets, DataFrames, Distributions, StatsBase

In [114]:
RDatasets.packages()

Row,Package,Title
,String15,String
1,COUNT,"Functions, data and code for count data."
2,Ecdat,Data sets for econometrics
3,HSAUR,A Handbook of Statistical Analyses Using R (1st Edition)
4,HistData,Data sets from the history of statistics and data visualization
5,ISLR,Data for An Introduction to Statistical Learning with Applications in R
6,KMsurv,"Data sets from Klein and Moeschberger (1997), Survival Analysis"
7,MASS,Support Functions and Datasets for Venables and Ripley's MASS
8,SASmixed,"Data sets from ""SAS System for Mixed Models"""
9,Zelig,Everyone's Statistical Software


In [115]:
RDatasets.datasets("ggplot2")

Row,Package,Dataset,Title,Rows,Columns
,String15,String31,String,Int64,Int64
1,ggplot2,diamonds,"Prices of 50,000 round cut diamonds",53940,10
2,ggplot2,economics,US economic time series.,478,6
3,ggplot2,midwest,Midwest demographics.,437,28
4,ggplot2,movies,Movie information and user ratings from IMDB.com.,58788,24
5,ggplot2,mpg,Fuel economy data from 1999 and 2008 for 38 popular models of car,234,11
6,ggplot2,msleep,An updated and expanded version of the mammals sleep dataset.,83,11
7,ggplot2,presidential,Terms of 10 presidents from Eisenhower to Bush W.,10,4
8,ggplot2,seals,Vector field of seal movements.,1155,4


In [116]:
iris=dataset("datasets", "iris")

Row,SepalLength,SepalWidth,PetalLength,PetalWidth,Species
,Float64,Float64,Float64,Float64,Cat…
1,5.1,3.5,1.4,0.2,setosa
2,4.9,3.0,1.4,0.2,setosa
3,4.7,3.2,1.3,0.2,setosa
4,4.6,3.1,1.5,0.2,setosa
5,5.0,3.6,1.4,0.2,setosa
6,5.4,3.9,1.7,0.4,setosa
7,4.6,3.4,1.4,0.3,setosa
8,5.0,3.4,1.5,0.2,setosa
9,4.4,2.9,1.4,0.2,setosa


In [117]:
vscodedisplay(iris)

# Dataframes

Un `dataframe` es una estructura de datos con filas y columnas similar a una hoja de cálculo.  Organiza los datos en una tabla bidimensional. Las columnas tienen nombres y contienen datos del mismo tipo. Con los dataframes se pueden manejar datos faltantes.

In [118]:
using DataFrames

## Creación de un dataframe

In [119]:
df1= DataFrame("Edad" => [20,21,19], "nombre" => ["Carlos", "Juliana", "Pedro"])

Row,Edad,nombre
,Int64,String
1,20,Carlos
2,21,Juliana
3,19,Pedro


In [120]:
df2=DataFrame(x=[1,2,3],y=["uno","dos","tres"])

Row,x,y
,Int64,String
1,1,uno
2,2,dos
3,3,tres


In [121]:
df3=DataFrame([1 0; 2 0], :auto)

Row,x1,x2
,Int64,Int64
1,1,0
2,2,0


In [122]:
mat = [1 2 4 5; 15 58 69 41; 23 21 26 69]
df4=DataFrame(mat, ["a","b","c","d"])

Row,a,b,c,d
,Int64,Int64,Int64,Int64
1,1,2,4,5
2,15,58,69,41
3,23,21,26,69


In [123]:
describe(df4)

Row,variable,mean,min,median,max,nmissing,eltype
,Symbol,Float64,Int64,Float64,Int64,Int64,DataType
1,a,13.0,1,15.0,23,0,Int64
2,b,27.0,2,21.0,58,0,Int64
3,c,33.0,4,26.0,69,0,Int64
4,d,38.3333,5,41.0,69,0,Int64


In [124]:
first(iris,5)

Row,SepalLength,SepalWidth,PetalLength,PetalWidth,Species
,Float64,Float64,Float64,Float64,Cat…
1,5.1,3.5,1.4,0.2,setosa
2,4.9,3.0,1.4,0.2,setosa
3,4.7,3.2,1.3,0.2,setosa
4,4.6,3.1,1.5,0.2,setosa
5,5.0,3.6,1.4,0.2,setosa


In [125]:
last(iris,4)

Row,SepalLength,SepalWidth,PetalLength,PetalWidth,Species
,Float64,Float64,Float64,Float64,Cat…
1,6.3,2.5,5.0,1.9,virginica
2,6.5,3.0,5.2,2.0,virginica
3,6.2,3.4,5.4,2.3,virginica
4,5.9,3.0,5.1,1.8,virginica


In [126]:
iris[4:8,:]

Row,SepalLength,SepalWidth,PetalLength,PetalWidth,Species
,Float64,Float64,Float64,Float64,Cat…
1,4.6,3.1,1.5,0.2,setosa
2,5.0,3.6,1.4,0.2,setosa
3,5.4,3.9,1.7,0.4,setosa
4,4.6,3.4,1.4,0.3,setosa
5,5.0,3.4,1.5,0.2,setosa


In [127]:
iris[:,2:4]

Row,SepalWidth,PetalLength,PetalWidth
,Float64,Float64,Float64
1,3.5,1.4,0.2
2,3.0,1.4,0.2
3,3.2,1.3,0.2
4,3.1,1.5,0.2
5,3.6,1.4,0.2
6,3.9,1.7,0.4
7,3.4,1.4,0.3
8,3.4,1.5,0.2
9,2.9,1.4,0.2


In [128]:
iris[5:10,1:4]

Row,SepalLength,SepalWidth,PetalLength,PetalWidth
,Float64,Float64,Float64,Float64
1,5.0,3.6,1.4,0.2
2,5.4,3.9,1.7,0.4
3,4.6,3.4,1.4,0.3
4,5.0,3.4,1.5,0.2
5,4.4,2.9,1.4,0.2
6,4.9,3.1,1.5,0.1


In [129]:
df3 = DataFrame(x1=rand(20),x2=rand(20),x3=rand(['a','b','c'],20))

Row,x1,x2,x3
,Float64,Float64,Char
1,0.892616,0.744865,a
2,0.487674,0.75282,b
3,0.354447,0.399235,b
4,0.118401,0.987515,a
5,0.897687,0.129962,a
6,0.193158,0.923899,c
7,0.335969,0.0393762,a
8,0.986072,0.0350748,a
9,0.545442,0.0162696,c


Vea [Think Julia](https://benlauwens.github.io/ThinkJulia.jl/latest/book.html) para saber más.