# Técnicas de conteo

In [54]:
using Combinatorics

Todos sabemos contar: 1,2,3,...., pero cuando lo que se va a contar es suficientemente grande se necesitan herramientas para que el conteo se haga en un tiempo prudentemente corto.

## Ejemplos

1. ¿Cuántos billetes tiene una lotería?
2. ¿De cuántas maneras se pueden entregar 5 cartas de una baraja?
3. ¿Cuántos números de teléfono fijo puede ofrecer una compañía?
4. ¿Cuántas claves tiene una tarjeta débito?

A continuación daremos algunas herramientas que se usarán para contar.

### Factorial

Para $n \in \mathbb{N}$ definimos n-factorial, $n!$, asi
$$
n!=n(n-1)(n-2)\cdots3.2.1=\prod_{i=0}^{n-1}n-i\\
0!=1
$$

In [1]:
factorial(5)

120

In [2]:
factorial(20)

2432902008176640000

### Manejo de excepciones

In [4]:
try 
    factorial(21) 
catch 
    println("no se puede calcular para n >20")
end
println("ensaye factorial(big(21))")

no se puede calcular para n >20
ensaye factorial(big(21))


In [4]:
factorial(big(21))

51090942171709440000

In [1]:
fac100 = factorial(big(100))

93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000

In [3]:
length(string(fac100))

158

### Combinatoria

Para $n$ y $k$ en  $\mathbb{N}$ definimos combinatoria $n,k$, así
$$
nCk=C(n,k)=\binom{n}{k}=\frac{n!}{k!(n-k)!}
$$
siempre que $0 \leq k \leq n$, siempre da un natural. También se llama *coeficiente binomial*.

In [6]:
binomial(10,3)

120

In [7]:
binomial(21,5)

20349

In [8]:
binomial(2,3) # no está definido, julia le da el valor de cero

0

### Permutación

Para $n$ y $k$ en $\mathbb{N}$, definimos permutación $n$,$k$, así
$$
nPk=P(n,k)=\frac{n!}{(n-k)!}
$$
siempre que $0 \leq k \leq n$

In [9]:
perm(n,k)=binomial(n,k)*factorial(big(k))

perm (generic function with 1 method)

In [10]:
perm(5,2)

20

### Teorema del Binomio

Para $n \in \mathbb{N}$, la n-ésima potencia de un binomio  $a+b$ está dada por
$$
(a+b)^{n}=\sum_{k=0}^{n}\binom{n}{k}a^{n-k}b^{k}=\binom{n}{0}a^{n}+\binom{n}{1}a^{n-1}{b}+\binom{n}{2}a^{n-2}b^{2}+\cdots + \binom{n}{n-1}ab^{n-1}+\binom{n}{n}b^{n}
$$

1. $(a+b)^2=a^2+2ab+b^2$
2. $(a+b)^3=a^3+3a^2b+3ab^2+b^3$
3. $(a+b)^4=a^4+4a3b+6a^2b^2+4ab^3+b^4$

$(a+b)^n$ tiene $n+1$ términos.

## Triángulo de Pascal

La función `tpascal(n)` construye el triángulo de Pascal hasta la n-ésima fila. 

In [11]:
tpascal(n)=[binomial(i,j) for i ∈ 0:n, j ∈ 0:n ]

tpascal (generic function with 1 method)

In [12]:
tpascal(5)

6×6 Matrix{Int64}:
 1  0   0   0  0  0
 1  1   0   0  0  0
 1  2   1   0  0  0
 1  3   3   1  0  0
 1  4   6   4  1  0
 1  5  10  10  5  1

In [13]:
tpascal(10)

11×11 Matrix{Int64}:
 1   0   0    0    0    0    0    0   0   0  0
 1   1   0    0    0    0    0    0   0   0  0
 1   2   1    0    0    0    0    0   0   0  0
 1   3   3    1    0    0    0    0   0   0  0
 1   4   6    4    1    0    0    0   0   0  0
 1   5  10   10    5    1    0    0   0   0  0
 1   6  15   20   15    6    1    0   0   0  0
 1   7  21   35   35   21    7    1   0   0  0
 1   8  28   56   70   56   28    8   1   0  0
 1   9  36   84  126  126   84   36   9   1  0
 1  10  45  120  210  252  210  120  45  10  1

In [14]:
fila_pascal(n)=[binomial(n,k) for k ∈ 0:n]

fila_pascal (generic function with 1 method)

In [15]:
fila_pascal(10)'

1×11 adjoint(::Vector{Int64}) with eltype Int64:
 1  10  45  120  210  252  210  120  45  10  1

$(a+b)^{10}=a^{10}+10a^9b+45a^8b^2+120a^7b^3+210a^6b^4+\cdots +10ab^9+b^{10}$

In [16]:
using LinearAlgebra, SparseArrays

In [17]:
sparse(tpascal(10))

11×11 SparseMatrixCSC{Int64, Int64} with 66 stored entries:
 1   ⋅   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋅   ⋅  ⋅
 1   1   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋅   ⋅  ⋅
 1   2   1    ⋅    ⋅    ⋅    ⋅    ⋅   ⋅   ⋅  ⋅
 1   3   3    1    ⋅    ⋅    ⋅    ⋅   ⋅   ⋅  ⋅
 1   4   6    4    1    ⋅    ⋅    ⋅   ⋅   ⋅  ⋅
 1   5  10   10    5    1    ⋅    ⋅   ⋅   ⋅  ⋅
 1   6  15   20   15    6    1    ⋅   ⋅   ⋅  ⋅
 1   7  21   35   35   21    7    1   ⋅   ⋅  ⋅
 1   8  28   56   70   56   28    8   1   ⋅  ⋅
 1   9  36   84  126  126   84   36   9   1  ⋅
 1  10  45  120  210  252  210  120  45  10  1

## Propiedades de los coeficientes binomiales

Para $n$ y $k$ $\in \mathbb{N}$ tales que $0 \leq k \leq n$, se cumple 


1.   $\displaystyle \binom{n}{k}=\frac{P(n,k)}{k!}$ 
2.  $\displaystyle \binom{n}{0}=1 $
3.  $\displaystyle \binom{n}{n}=1 $
4. $\displaystyle \binom{n}{1}=n $
5. $\displaystyle \binom{n}{n-1}=n $
6. $ \displaystyle \binom{n}{k}=\binom{n}{n-k} $
7. $\displaystyle \binom{n}{k}+\binom{n}{k+1}=\binom{n+1}{k+1} $
8. $ \displaystyle \sum_{k=0}^{n}\binom{n}{k}=\binom{n}{0}+\binom{n}{1}+\binom{n}{2}+\cdots + \binom{n}{n-1} +\binom{n}{n} =2^{n} $
9. $ \displaystyle \sum_{k=0}^{n}\binom{n}{k}(-1)^{k}=\binom{n}{0}-\binom{n}{1}+\binom{n}{2}-\cdots + \binom{n}{n-1} \pm \binom{n}{n} =0 $



In [18]:
A=tpascal(10)
sum(A,dims=2)'

1×11 adjoint(::Matrix{Int64}) with eltype Int64:
 1  2  4  8  16  32  64  128  256  512  1024

La suma de las filas del triángulo de Pascal.

## Principio fundamental del conteo

Sean m eventos que pueden suceder de $n_1,n_2,\cdots,n_m$ maneras cada uno respectivamente, entonces los m eventos juntos pueden suceder de 
$$
n_1*n_2* \cdots *n_m
$$
maneras

## Ejercicio

¿Cuántas placas de carro hay si constan de tres letras diferentes  y de tres dígitos y además el primer dígito no es cero?

> Se considera el alfabeto inglés de 26 letras, los dígitos son 10: 0,1,2,3,4,5,6,7,8,9 para hacer los ejercicios

In [19]:
26*25*24*9*10*10

14040000

Las placas completas:

In [20]:
26*26*26*10*10*10

17576000

## Ejercicio: 
Una lotería tiene 4 dígitos y 200 series,¿Cuántos billetes hay?

In [21]:
10*10*10*10*200

2000000

In [22]:
1/2_000_000 # probabilidad de ganar

5.0e-7

In [23]:
0.0000005

5.0e-7

2_000_000 de semanas $\approx$ 38356 años

In [24]:
365/7 # semanas del año

52.142857142857146

In [25]:
2000000/(365/7) #años

38356.16438356164

## Ejercicio: Baloto
Se tienen 45 balotas numeradas de 1 a 45 y se extraen 6 balotas una tras otra y sin reemplazo, ¿Cuántos balotos diferentes se pueden hacer?

In [26]:
binomial(45,6)

8145060

En el baloto no hay orden, es decir usted gana con los números en cualquier orden, en la lotería si hay orden, para ganar debe tener los números en el orden que salieron. Para generar un baloto de 45 sacar 6:

In [27]:
using StatsBase
sample(1:45,6,replace=false,ordered=false)

6-element Vector{Int64}:
 45
 16
 31
 13
  1
 27

In [28]:
binomial(43,5)*16 # baloto actual

15401568

## Muestras
Dado un conjunto de $n$ elementos, obtener muestras de tamaño $k$, con $0 \leq k \leq n$. Hay 4 formas:

1. muestra ordenada con reemplazo MOR
2. muestra ordenada sin remplazo MOsR
3. muestra sin orden con reemplazo MsOR
4. muestra sin orden sin reemplazo MsOsR

### Ejemplo
Sea un conjunto con $n=5$ elementos $\{1,2,3,4,5\}$, saquemos muestras de tamaño $k=2$.

### Muestra ordenada con reemplazo

In [29]:
MOR=[(i,j) for i ∈ 1:5,j ∈ 1:5]

5×5 Matrix{Tuple{Int64, Int64}}:
 (1, 1)  (1, 2)  (1, 3)  (1, 4)  (1, 5)
 (2, 1)  (2, 2)  (2, 3)  (2, 4)  (2, 5)
 (3, 1)  (3, 2)  (3, 3)  (3, 4)  (3, 5)
 (4, 1)  (4, 2)  (4, 3)  (4, 4)  (4, 5)
 (5, 1)  (5, 2)  (5, 3)  (5, 4)  (5, 5)

> **orden** significa que $(1, 2)$ y $(2, 1)$ se cuentan por aparte, de lo contrario se cuentan una sola vez

> **reemplazo** significa que las muestras $(1, 1), (2, 2),..$ pueden aparecer

In [30]:
length(MOR)

25

In [31]:
5^2

25

### Muestra ordenada sin reemplazo

In [32]:
MOsR=[(i,j) for i ∈ 1:5,j ∈ 1:5 if i != j]
reshape(MOsR,5,4)

5×4 Matrix{Tuple{Int64, Int64}}:
 (2, 1)  (3, 2)  (4, 3)  (5, 4)
 (3, 1)  (4, 2)  (5, 3)  (1, 5)
 (4, 1)  (5, 2)  (1, 4)  (2, 5)
 (5, 1)  (1, 3)  (2, 4)  (3, 5)
 (1, 2)  (2, 3)  (3, 4)  (4, 5)

In [33]:
length(MOsR)

20

In [34]:
perm(5,2)

20

### Muestra sin orden con reemplazo

In [35]:
MsOR=[[i,j] for i ∈ 1:5,j ∈ 1:5 if i ≥ j]
reshape(MsOR,5,3)

5×3 Matrix{Vector{Int64}}:
 [1, 1]  [2, 2]  [4, 3]
 [2, 1]  [3, 2]  [5, 3]
 [3, 1]  [4, 2]  [4, 4]
 [4, 1]  [5, 2]  [5, 4]
 [5, 1]  [3, 3]  [5, 5]

In [36]:
length(MsOR)

15

In [37]:
binomial(5+2-1,2)

15

### Muestra sin orden sin reemplazo

In [38]:
MsOsR=[[i,j] for i ∈ 1:5,j ∈ 1:5 if i > j]
reshape(MsOsR,5,2)

5×2 Matrix{Vector{Int64}}:
 [2, 1]  [4, 2]
 [3, 1]  [5, 2]
 [4, 1]  [4, 3]
 [5, 1]  [5, 3]
 [3, 2]  [5, 4]

In [39]:
length(MsOsR)

10

In [40]:
binomial(5,2)

10

## Fórmulas de conteo 

| ORDEN     | Muestra | Fórmula           |
|:---------:|:-------:|:-----------------:|
|   orden   |   MOR   |        $n^k$      |
|   orden   |   MOsR  |      $P(n,k)$     |
| sin orden |   MsOR  | $\binom{n+k-1}{k}$|
| sin orden |  MsOsR  |   $\binom{n}{k}$  |


## Ejercicio
¿De cuántas maneras pueden hacer fila 6 personas para subirse a un bus?


n=6, k=6
Para saber si hay **orden** se imagina un caso: ABCDEF, intercambie dos: BACDEF, ¿Son dos filas o es la misma fila? Son dos filas diferentes, hay orden. Para ver reemplazo AABCDE, no es posible, no hay reemplazo. Cuando hay orden puede usar el principio fundamental del conteo.


In [41]:
perm(6,6)

720

In [42]:
6*5*4*3*2*1

720

¿De cuántas maneras si dos personas determinadas se suben juntas?
Supongamos que se suben primera y segunda:

In [43]:
2*1*4*3*2*1*5

240

¿De cuántas maneras si ya no van juntas?

In [44]:
720-240

480

## Ejercicio
En un curso hay 6 mujeres y 4 hombres, ¿Cuántos comités de 5 personas se pueden formar?


n=10, k=5, ABCDE, BACDE, no hay orden pues es el mismo comité, AABCD , no  puede estar la misma persona dos veces, no hay reemplazo.
$$\binom{10}{5}$$

In [45]:
binomial(10,5)

252

¿Cuántos comités tienen exactamente dos mujeres?
$$\binom{6}{2}\binom{4}{3}$$

In [46]:
binomial(6,2)*binomial(4,3)

60

¿Cuántos comités tienen a lo más dos mujeres?
$$\binom{6}{2}\binom{4}{3}+\binom{6}{1}\binom{4}{4}=66$$

In [47]:
binomial(6,2)*binomial(4,3) + binomial(6,1)*binomial(4,4)

66

## Ejercicio
Una clave tiene dos letras y 4 dígitos, ¿Cuántas claves hay?

In [48]:
26*26*10*10*10*10

6760000

¿Cuántas claves tienen letras iguales?

In [49]:
26*1*10*10*10*10

260000

¿Cuántas claves tienen números diferentes?

In [50]:
26*26*10*9*8*7

3407040

¿Cuántas claves tienen letras diferentes y números iguales?

In [51]:
26*25*10*1*1*1

6500

¿Cuántas claves empiezan con vocal y terminan con un número par?

In [52]:
5*26*10*10*10*5

650000

## Ejercicio
Baraja francesa [baraja francesa](https://es.wikipedia.org/wiki/Baraja_francesa)

Tiene 13 diamantes(rojas), 13 picas(negras), 13, corazones(rojas) y 13 tréboles(negras), hay 26 cartas negras, hay 26 cartas rojas, hay 12 figuras y hay 4 ases.

Se saca una carta de una baraja de 52 cartas, ¿De cuantas maneras puede salir una figura roja? 

n=52, k=1, en las cartas no hay orden, no hay reemplazo. 

## Ejercicio

Se tienen 4 banderas rojas, 5 azules y 6 verdes. Se ponen en fila para formar señales, ¿Cuántas señales diferentes se pueden formar?

$$
\binom{15}{4,5,6}=\frac{15!}{4!5!6!}=630630
$$

In [55]:
multinomial(4,5,6)

630630

## Coeficiente multinomial

Para naturales $n,n_1,n_2,\cdots ,n_k$, tales que $n_1+n_2+\cdots+n_k=n$ se define

$\binom{n}{n_1,n_2,\cdots ,n_k}=\frac{n!}{n_1!n_2!\cdots n_k!}$

llamado *coeficiente multinomial*. [multinomial](https://en.wikipedia.org/wiki/Multinomial_theorem)



$\binom{9}{2,3,4}$ se calcula en julia:

In [56]:
multinomial(2,3,4)

1260

In [57]:
factorial(9)/(factorial(2)*factorial(3)*factorial(4))

1260.0

## Ejercicio:

¿De cuántas maneras se pueden dividir 15 personas en tres grupos de 7, 6 y 2 personas ?

$$
\binom{15}{7}\binom{8}{6}\binom{2}{2}
$$

In [ ]:
binomial(15,7)*binomial(8,6)*binomial(2,2)

## Funciones en julia

In [5]:
function f(x,y)
    x+y
end
f(4,6)

10

In [6]:
g(x,y)=x*y
g(3,4)

12

## Comprehensions. Construcción de arreglos

In [7]:
[(i, j) for i=1:3 for j=1:i]

6-element Vector{Tuple{Int64, Int64}}:
 (1, 1)
 (2, 1)
 (2, 2)
 (3, 1)
 (3, 2)
 (3, 3)

In [8]:
[(i, j) for i=1:3 for j=1:i if i+j == 4]

2-element Vector{Tuple{Int64, Int64}}:
 (2, 2)
 (3, 1)

In [9]:
[ x^2+y for x in 0:3, y in 1:4]

4×4 Matrix{Int64}:
  1   2   3   4
  2   3   4   5
  5   6   7   8
 10  11  12  13